export const runtime="nodejs";
function decodeEntities(t){return t.replaceAll("&nbsp;"," ").replaceAll("&amp;","&").replaceAll("&euro;","€").replaceAll("&auml;","ä").replaceAll("&ouml;","ö").replaceAll("&aring;","å").replaceAll("&Auml;","Ä").replaceAll("&Ouml;","Ö").replaceAll("&Aring;","Å").replaceAll("&quot;",'"');}
function cleanText(html){return decodeEntities(html).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function numAfter(text,labels,max=140){for(const label of labels){const i=text.indexOf(label);if(i<0)continue;const slice=text.slice(i+label.length,i+label.length+max);let started=false,raw="";for(const ch of slice){const ok="0123456789 ,.".includes(ch);if(!started&&"0123456789".includes(ch))started=true;if(started&&ok)raw+=ch;if(started&&!ok)break;}const v=Number(raw.replaceAll(" ","").replace(",","."));if(Number.isFinite(v))return v;}return null;}
function parseYear(text){const m=text.match(/(rakennusvuosi|valmistunut|rakennettu)[^\d]*(19\d{2}|20\d{2})/i);return m?Number(m[2]):null;}
function parseFields(raw){const text=raw.toLowerCase();const f={};let v;
v=numAfter(text,["velaton myyntihinta","velaton hinta"]); if(v!==null)f.debtFreePrice=Math.round(v);
v=numAfter(text,["myyntihinta"]); if(v!==null)f.sellingPrice=Math.round(v);
v=numAfter(text,["velkaosuus","lainaosuus"]); if(v!==null){f.debtShare=Math.round(v);f.hasDebtShare=v>0?"yes":"no";}
v=numAfter(text,["hoitovastike"]); if(v!==null)f.maintenanceFee=Math.round(v);
v=numAfter(text,["rahoitusvastike","pääomavastike"]); if(v!==null){f.financingFee=Math.round(v);f.hasDebtShare=v>0||f.debtShare>0?"yes":"no";}
v=numAfter(text,["vuokra"]); if(v!==null&&v<10000)f.rent=Math.round(v);
v=numAfter(text,["asuinpinta-ala","pinta-ala"]); if(v!==null&&v>5&&v<1000)f.size=Math.round(v*10)/10;
v=parseYear(text); if(v!==null)f.buildYear=v;
if(text.includes("kerrostalo"))f.buildingType="apartment"; if(text.includes("rivitalo"))f.buildingType="terraced"; if(text.includes("luhtitalo"))f.buildingType="loft";
if(text.includes("oma tontti"))f.landType="own"; if(text.includes("vuokratontti")||text.includes("tontin vuokra")||text.includes("tontinvuokra"))f.landType="leased_city"; if(text.includes("yksityinen vuokratontti"))f.landType="leased_private";
if(text.includes("kaukolämpö"))f.heatingType="district"; if(text.includes("maalämpö"))f.heatingType="geothermal"; if(text.includes("sähkölämmitys")||text.includes("suora sähkö"))f.heatingType="electric";
if(text.includes("tasakatto"))f.flatRoof="yes"; if(text.includes("linjasaneeraus")||text.includes("putkiremontti"))f.upcomingPipeRenovation="full_line"; if(text.includes("sukitus")||text.includes("pinnoitus"))f.upcomingPipeRenovation="pipe_rehab"; if(text.includes("kattoremontti")||text.includes("vesikatto"))f.upcomingRoofRenovation="roof"; if(text.includes("julkisivuremontti"))f.upcomingFacadeRenovation="facade"; if(text.includes("parvekeremontti"))f.upcomingBalconyRenovation="balcony"; if(text.includes("ikkunaremontti"))f.upcomingWindowRenovation="windows"; if(text.includes("entinen vuokratalo")||text.includes("vanha vuokratalo"))f.oldRentalBuilding="yes"; return f;}
export async function GET(request){const {searchParams}=new URL(request.url);const url=searchParams.get("url");if(!url)return Response.json({error:"URL puuttuu."},{status:400});if(!url.includes("etuovi.com")&&!url.includes("oikotie.fi"))return Response.json({error:"Sallittu vain Etuovi- tai Oikotie-linkeille."},{status:400});try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Accept-Language":"fi-FI,fi;q=0.9,en;q=0.8"},cache:"no-store"});const html=await r.text();if(!r.ok)return Response.json({error:`Ilmoitussivun haku epäonnistui: ${r.status}`},{status:502});const rawText=cleanText(html);const fields=parseFields(rawText);return Response.json({sourceUrl:url,fields,rawText,foundKeys:Object.keys(fields)});}catch(e){return Response.json({error:e.message||"URL-parseri epäonnistui."},{status:500});}}