import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { analysisFacts, analysisTitle, showFloor } from "../src/core/analysis/analysis-presentation.ts";
import { parseBuildingType, parseFloor, parseRoomConfiguration } from "../src/core/parser/normalization.ts";
import { parseListingText } from "../src/core/parser/listing-parser.ts";

test("otsikko käyttää osoitetta, ilmoitusotsikkoa ja turvallista fallbackia", () => { assert.equal(analysisTitle({ address: "Keskuskatu 12 A 4", city: "Vaasa" }), "Keskuskatu 12 A 4, Vaasa"); assert.equal(analysisTitle({ listingTitle: "Kolmio keskustassa" }), "Kolmio keskustassa"); assert.equal(analysisTitle({}), "Analysoitu sijoituskohde"); });
test("perustietorivi sisältää vain saatavilla olevat arvot", () => { assert.deepEqual(analysisFacts({ roomDescription: "3h + k + s", areaSqm: 99.6, buildingType: "terraced", constructionYear: 1964, floor: "1 / 2" }), ["3h + k + s", "99,6 m²", "Rivitalo", "Rakennusvuosi 1964"]); assert.deepEqual(analysisFacts({ areaSqm: 45, buildingType: "apartment", floor: "2 / 5" }), ["45 m²", "Kerrostalo", "Kerros 2 / 5"]); });
test("huonejako, rakennustyyppi ja kerros normalisoituvat", () => { assert.equal(parseRoomConfiguration("3h, k, s"), "3h + k + s"); assert.equal(parseRoomConfiguration("2 huonetta ja keittiö"), "2h + k"); assert.equal(parseBuildingType("Valoisa rivitaloasunto"), "terraced"); assert.equal(parseBuildingType("Kerrostalo keskustassa"), "apartment"); assert.equal(parseFloor("katutaso"), "Katutaso"); assert.equal(showFloor("terraced", "1 / 2"), false); assert.equal(showFloor("apartment", "2 / 5"), true); });
test("huonejako ja rakennustyyppi johdetaan ilmoituksen otsikosta", () => { const result = parseListingText("", "etuovi", [{ field: "listingTitle", value: "3h + k + s, rivitalo Vaasa", label: "otsikko", excerpt: "h1" }]); assert.equal(result.findings.find((item) => item.field === "roomDescription")?.normalizedValue, "3h + k + s"); assert.equal(result.findings.find((item) => item.field === "buildingType")?.normalizedValue, "terraced"); });
test("tontin omistusmuodot parsitaan automaattisesti", () => { for (const [input, expected] of [["Oma tontti", "owned"], ["Vuokratontti", "leased"], ["Valinnainen vuokratontti", "optional_leasehold"]] as const) assert.equal(parseListingText(`Tontin omistusmuoto: ${input}`).findings[0]?.normalizedValue, expected); });
test("saatavilla oleva kuntotieto parsitaan", () => { assert.equal(parseListingText("Asunnon kunto: Hyvä").findings.find((item) => item.field === "condition")?.normalizedValue, "Hyvä"); });
test("sivujärjestys alkaa johtopäätöksestä ja lähteet ovat lopussa", async () => { const workspace = await readFile(new URL("../src/components/property/property-workspace.tsx", import.meta.url), "utf8"); const score = workspace.indexOf("<InvestmentOverallScore"); const details = workspace.indexOf("<PropertyDetailsCard"); const sources = workspace.indexOf("<ImportSourceReview"); assert.ok(score > 0 && details > score && sources > details); assert.doesNotMatch(workspace, />Uusi kohde</); for (const value of ["AnalysisHighlights", "KeyMetrics", "Analyysin lähtötiedot"]) assert.ok(workspace.includes(value)); });
test("puuttuvat kentät ja suuret tonttilomakkeet eivät renderöidy", async () => { const details = await readFile(new URL("../src/components/property/details-cards.tsx", import.meta.url), "utf8"); assert.doesNotMatch(details, /SelectField|SelectTrigger|placeholder="Ei tiedossa"/); assert.match(details, /if \(present\(importedData\.landOwnership\)\)/); assert.match(details, /if \(present\(importedData\.condition\)\)/); });
