import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { adaptInvestmentScore } from "../src/core/analysis/investment-score-adapter.ts";
import { clampInvestmentScore, getInvestmentRating, scoreMarkerPosition } from "../src/core/analysis/investment-overall-score.ts";

test("pisterajat mapitetaan arvosanoihin ja keskitettyihin väreihin", () => { for (const [score, grade] of [[100, "A+"], [90, "A+"], [89, "A"], [80, "A"], [79, "B"], [70, "B"], [69, "C"], [60, "C"], [59, "D"], [45, "D"], [44, "E"], [0, "E"]] as const) { const rating = getInvestmentRating(score); assert.equal(rating.grade, grade); assert.match(rating.color, /^#[0-9a-f]{6}$/i); } });
test("virheelliset pisteet clampataan turvallisesti", () => { assert.equal(clampInvestmentScore(-10), 0); assert.equal(clampInvestmentScore(125), 100); assert.equal(clampInvestmentScore(Number.NaN), 0); assert.equal(clampInvestmentScore(undefined), 0); });
test("marker pysyy palkin sisällä edge caseissa", () => { assert.equal(scoreMarkerPosition(0), "clamp(6px, 0%, calc(100% - 6px))"); assert.equal(scoreMarkerPosition(1), "clamp(6px, 1%, calc(100% - 6px))"); assert.equal(scoreMarkerPosition(50), "clamp(6px, 50%, calc(100% - 6px))"); assert.equal(scoreMarkerPosition(99), "clamp(6px, 99%, calc(100% - 6px))"); assert.equal(scoreMarkerPosition(100), "clamp(6px, 100%, calc(100% - 6px))"); });
test("adapteri käyttää nykyisiä analyysitietoja ja tuottaa neljä osa-arviota", () => { const strong = adaptInvestmentScore({ debtFreePrice: 100_000, currentRentMonthly: 750, maintenanceFeeMonthly: 200, financingFeeMonthly: 0, companyLoanShare: 0 }); const weak = adaptInvestmentScore({ debtFreePrice: 200_000, currentRentMonthly: 500, maintenanceFeeMonthly: 350, financingFeeMonthly: 200, companyLoanShare: 120_000 }); assert.ok(strong.score > weak.score); assert.deepEqual(Object.keys(strong.subScores ?? {}), ["yield", "cashFlow", "housingCompanyRisk", "financing"]); });
test("sijoitusmahdollisuuden sanalliset luokat vastaavat pisterajoja", () => { assert.equal(getInvestmentRating(95).label, "Erinomainen sijoitusmahdollisuus"); assert.equal(getInvestmentRating(85).label, "Erittäin hyvä sijoitusmahdollisuus"); assert.equal(getInvestmentRating(75).label, "Hyvä sijoitusmahdollisuus"); assert.equal(getInvestmentRating(65).label, "Kohtalainen sijoitusmahdollisuus"); assert.equal(getInvestmentRating(55).label, "Heikko sijoitusmahdollisuus"); assert.equal(getInvestmentRating(35).label, "Ei suositeltava sijoitus"); });
test("komponentti renderöi vaakapalkin, markerin ja null-tilan ilman kaarimittaria", async () => { const component = await readFile(new URL("../src/components/property/investment-overall-score.tsx", import.meta.url), "utf8"); assert.match(component, /role="progressbar"/); assert.match(component, /data-score-progress/); assert.match(component, /data-score-marker/); assert.match(component, /Arvio muodostuu lähtötietojen täydentämisen jälkeen/); assert.match(component, /Kohteen markkinahintaa ei arvioida tässä analyysissä/); assert.match(component, /Voit tilata markkinahinta-analyysin erikseen/); assert.doesNotMatch(component, /Arvio perustuu kohteen hintaan/); assert.match(component, /scoreMissing/); assert.doesNotMatch(component, /<svg|gaugeArcPath|gaugePoint|viewBox/); });
