import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { effectiveAnnualRent, occupancyFromVacancyMonths, vacancyMonthsFromOccupancyRate } from "../src/core/calculations/occupancy.ts";
import { calculateInvestmentAnalysis } from "../src/core/calculations/investment-analysis.ts";
import { synchronizePrices } from "../src/core/calculations/purchase-price.ts";

test("velaton hinta päivittää myyntihinnan", () => { assert.deepEqual(synchronizePrices({ debtFreePrice: 0, salePrice: 0, companyLoanShare: 15_000 }, "debtFreePrice", 158_989, "debtFreePrice"), { debtFreePrice: 158_989, salePrice: 143_989, companyLoanShare: 15_000 }); });
test("myyntihinta päivittää velattoman hinnan", () => { assert.deepEqual(synchronizePrices({ debtFreePrice: 0, salePrice: 0, companyLoanShare: 15_000 }, "salePrice", 144_000, "debtFreePrice"), { debtFreePrice: 159_000, salePrice: 144_000, companyLoanShare: 15_000 }); });
test("yhtiölaina säilyttää viimeksi ensisijaisen hintakentän", () => { assert.deepEqual(synchronizePrices({ debtFreePrice: 159_000, salePrice: 144_000, companyLoanShare: 15_000 }, "companyLoanShare", 20_000, "debtFreePrice"), { debtFreePrice: 159_000, salePrice: 139_000, companyLoanShare: 20_000 }); assert.deepEqual(synchronizePrices({ debtFreePrice: 159_000, salePrice: 144_000, companyLoanShare: 15_000 }, "companyLoanShare", 20_000, "salePrice"), { debtFreePrice: 164_000, salePrice: 144_000, companyLoanShare: 20_000 }); });
test("38 000 euron velaton hinta säilyttää 14 318 euron yhtiölainan hintasuhteen", () => { assert.deepEqual(synchronizePrices({ debtFreePrice: 38_000, salePrice: 23_682, companyLoanShare: 14_318 }, "debtFreePrice", 38_000, "debtFreePrice"), { debtFreePrice: 38_000, salePrice: 23_682, companyLoanShare: 14_318 }); });

test("tyhjäkäyntikuukaudet muunnetaan käyttöasteeksi ja clampataan", () => { assert.deepEqual(occupancyFromVacancyMonths(0), { vacancyMonths: 0, occupiedMonths: 12, occupancyRate: 1, occupancyRatePercent: 100 }); assert.deepEqual(occupancyFromVacancyMonths(undefined), { vacancyMonths: 0, occupiedMonths: 12, occupancyRate: 1, occupancyRatePercent: 100 }); assert.equal(occupancyFromVacancyMonths(0.5).occupancyRate, 11.5 / 12); assert.equal(occupancyFromVacancyMonths(1).occupancyRate, 11 / 12); assert.equal(occupancyFromVacancyMonths(2).occupancyRate, 10 / 12); assert.equal(occupancyFromVacancyMonths(-2).vacancyMonths, 0); assert.equal(occupancyFromVacancyMonths(15).vacancyMonths, 12); assert.equal(vacancyMonthsFromOccupancyRate(97), 0.5); });
test("toteutuva vuosivuokra käyttää vuokrattuja kuukausia", () => { assert.equal(effectiveAnnualRent(750, 1), 8_250); assert.equal(effectiveAnnualRent(750, 12), 0); });
test("nollan kuukauden tyhjäkäynti käyttää 12 kuukauden vuokraa eikä aiheuta tyhjäkäyntirangaistusta", () => { const result = calculateInvestmentAnalysis({ debtFreePrice: 100_000, salePrice: 100_000, companyLoanShare: 0, monthlyRent: 750, maintenanceFeeMonthly: 200, financingFeeMonthly: 0, vacancyMonths: 0, bankLoanAmount: 60_000, annualInterestRate: 4, loanTermYears: 20, collateralValue: 70_000 }); assert.equal(result.effectiveAnnualRent, 9_000); assert.equal(result.warningFactors?.some((item) => /tyhjäkäynt/i.test(item)), false); });

test("hintakenttä käyttää vakaata lokalisoitua tekstiluonnosta eikä näytä normaalia hintavirhettä", async () => { const purchase = await readFile(new URL("../src/components/property/purchase-card.tsx", import.meta.url), "utf8"); const field = await readFile(new URL("../src/components/property/localized-number-field.tsx", import.meta.url), "utf8"); assert.match(purchase, /LocalizedNumberField/); assert.match(field, /useState\(\(\) => formatValue/); assert.match(field, /onBlur=\{commit\}/); assert.doesNotMatch(purchase, /Hintatiedot eivät täsmää/); });
test("käyttöaste näkyy tyhjäkäyntikuukausina", async () => { const source = await readFile(new URL("../src/components/property/assumptions-card.tsx", import.meta.url), "utf8"); assert.match(source, /Arvioitu tyhjäkäynti/); assert.match(source, /kk \/ vuosi/); assert.doesNotMatch(source, /label="Käyttöaste"|suffix="%"[^\n]*occupancy/); });
test("työtila käyttää keskitettyä nollaoletusta ja huomio näkyy vain nolla-arvolla", async () => { const [workspace, assumptions] = await Promise.all([readFile(new URL("../src/components/property/property-workspace.tsx", import.meta.url), "utf8"), readFile(new URL("../src/components/property/assumptions-card.tsx", import.meta.url), "utf8")]); assert.match(workspace, /vacancyMonths: DEFAULT_VACANCY_MONTHS/); assert.match(assumptions, /values\.vacancyMonths === 0/); assert.match(assumptions, /Huomioi tyhjäkäynti/); assert.match(assumptions, /täydellä vuokrausasteella \(12 kk\/vuosi\)/); });
test("kattavuuslista sisältää olennaiset asiakirjat ja oikean analyysikytkennän", async () => { const source = await readFile(new URL("../src/components/property/analysis-coverage-card.tsx", import.meta.url), "utf8"); for (const text of ["Isännöitsijäntodistus", "Lisää asiakirja taloyhtiön talouden analysoimiseksi.", "Lisää asiakirja tulevien korjausten arvioimiseksi.", "Lisää asiakirja omistuspohjan tarkistamiseksi.", "Lisää asiakirja", "Analysoidaan…", "Analysoitu", "Yritä uudelleen"]) assert.ok(source.includes(text)); assert.doesNotMatch(source, /Energiatodistus|Avaa:/); assert.match(source, /analyzePropertyDocument\(file, kind\)/); assert.match(source, /onDocumentAnalyzed/); assert.doesNotMatch(source, /onDocumentAdded|queueMicrotask/); assert.match(source, /sm:flex-row/); assert.match(source, /w-full sm:w-auto/); });
