import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { effectiveAnnualRent, occupancyFromVacancyMonths, vacancyMonthsFromOccupancyRate } from "../src/core/calculations/occupancy.ts";
import { synchronizePrices } from "../src/core/calculations/purchase-price.ts";

test("velaton hinta päivittää myyntihinnan", () => { assert.deepEqual(synchronizePrices({ debtFreePrice: 0, salePrice: 0, companyLoanShare: 15_000 }, "debtFreePrice", 158_989, "debtFreePrice"), { debtFreePrice: 158_989, salePrice: 143_989, companyLoanShare: 15_000 }); });
test("myyntihinta päivittää velattoman hinnan", () => { assert.deepEqual(synchronizePrices({ debtFreePrice: 0, salePrice: 0, companyLoanShare: 15_000 }, "salePrice", 144_000, "debtFreePrice"), { debtFreePrice: 159_000, salePrice: 144_000, companyLoanShare: 15_000 }); });
test("yhtiölaina säilyttää viimeksi ensisijaisen hintakentän", () => { assert.deepEqual(synchronizePrices({ debtFreePrice: 159_000, salePrice: 144_000, companyLoanShare: 15_000 }, "companyLoanShare", 20_000, "debtFreePrice"), { debtFreePrice: 159_000, salePrice: 139_000, companyLoanShare: 20_000 }); assert.deepEqual(synchronizePrices({ debtFreePrice: 159_000, salePrice: 144_000, companyLoanShare: 15_000 }, "companyLoanShare", 20_000, "salePrice"), { debtFreePrice: 164_000, salePrice: 144_000, companyLoanShare: 20_000 }); });

test("tyhjäkäyntikuukaudet muunnetaan käyttöasteeksi ja clampataan", () => { assert.deepEqual(occupancyFromVacancyMonths(0), { vacancyMonths: 0, occupiedMonths: 12, occupancyRate: 1, occupancyRatePercent: 100 }); assert.equal(occupancyFromVacancyMonths(1).occupancyRate, 11 / 12); assert.equal(occupancyFromVacancyMonths(2).occupancyRate, 10 / 12); assert.equal(occupancyFromVacancyMonths(-2).vacancyMonths, 0); assert.equal(occupancyFromVacancyMonths(15).vacancyMonths, 12); assert.equal(vacancyMonthsFromOccupancyRate(97), 0); });
test("toteutuva vuosivuokra käyttää vuokrattuja kuukausia", () => { assert.equal(effectiveAnnualRent(750, 1), 8_250); assert.equal(effectiveAnnualRent(750, 12), 0); });

test("hintakenttä säilyttää tekstiluonnoksen kirjoittamisen ajan eikä näytä normaalia hintavirhettä", async () => { const source = await readFile(new URL("../src/components/property/purchase-card.tsx", import.meta.url), "utf8"); assert.match(source, /useState\(\(\) => formatDraft\(value\)\)/); assert.match(source, /onBlur=\{commit\}/); assert.doesNotMatch(source, /Hintatiedot eivät täsmää/); });
test("käyttöaste näkyy tyhjäkäyntikuukausina", async () => { const source = await readFile(new URL("../src/components/property/assumptions-card.tsx", import.meta.url), "utf8"); assert.match(source, /Arvioitu tyhjäkäynti/); assert.match(source, /kk \/ vuosi/); assert.doesNotMatch(source, /label="Käyttöaste"|suffix="%"[^\n]*occupancy/); });
test("kattavuuslista sisältää kolme olennaista asiakirjaa ja selkeät toiminnot", async () => { const source = await readFile(new URL("../src/components/property/analysis-coverage-card.tsx", import.meta.url), "utf8"); for (const text of ["Lisää asiakirja taloyhtiön talouden analysoimiseksi.", "Lisää asiakirja tulevien korjausten arvioimiseksi.", "Lisää asiakirja omistuspohjan tarkistamiseksi.", "Lisää asiakirja", "Analysoidaan…", "Analysoitu", "Yritä uudelleen"]) assert.ok(source.includes(text)); assert.doesNotMatch(source, /Energiatodistus|Avaa:/); assert.match(source, /setStates/); assert.match(source, /onDocumentAdded/); assert.match(source, /sm:flex-row/); assert.match(source, /w-full sm:w-auto/); });
