"use client";

import { FileText, Keyboard, Search } from "lucide-react";
import { useRef } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { brandName } from "@/core/i18n/display-values";

export function NewPropertyStart({ onListing, onDocuments, onManual }: { onListing: () => void; onDocuments: (files: FileList | null) => void; onManual: () => void }) {
  const fileInput = useRef<HTMLInputElement>(null);
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,var(--color-success-soft),transparent_34%)] px-4 py-8 md:px-8 md:py-14"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-success text-white"><Search className="size-5" /></div><div><p className="font-semibold tracking-tight">{brandName}</p><Badge variant="outline" className="mt-1 bg-background">Ennakkoversio</Badge></div></div></header><section className="mx-auto mt-16 max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-success">Uusi analyysi</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Aloita uusi kohde</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">Valitse sinulle nopein tapa. Voit täydentää kohdetta myöhemmin asiakirjoilla ja omilla tiedoillasi.</p></section><section className="mt-10 grid gap-5 lg:grid-cols-3"><Card className="relative border-success/30 ring-2 ring-success/15"><Badge className="absolute right-4 top-4 bg-success text-white">Suositeltu</Badge><CardHeader className="pt-10"><div className="mb-3 grid size-10 place-items-center rounded-lg bg-success-soft text-success"><Search /></div><CardTitle>Hae tiedot myynti-ilmoituksesta</CardTitle><CardDescription className="min-h-12">Liitä Etuovi- tai Oikotie-linkki, niin kohteen tiedot haetaan automaattisesti.</CardDescription></CardHeader><CardContent><Button className="w-full" size="lg" onClick={onListing}>Hae tiedot</Button></CardContent></Card><Card><CardHeader className="pt-10"><div className="mb-3 grid size-10 place-items-center rounded-lg bg-muted text-foreground"><FileText /></div><CardTitle>Lisää asiakirjat</CardTitle><CardDescription className="min-h-12">Lataa esimerkiksi myyntiesite, isännöitsijäntodistus, tilinpäätös tai yhtiöjärjestys.</CardDescription></CardHeader><CardContent><input ref={fileInput} type="file" multiple className="sr-only" aria-label="Valitse lisättävät asiakirjat" onChange={(event) => onDocuments(event.currentTarget.files)} /><Button className="w-full" variant="outline" size="lg" onClick={() => fileInput.current?.click()}>Lisää asiakirjat</Button></CardContent></Card><Card><CardHeader className="pt-10"><div className="mb-3 grid size-10 place-items-center rounded-lg bg-muted text-foreground"><Keyboard /></div><CardTitle>Syötä tiedot itse</CardTitle><CardDescription className="min-h-12">Luo uusi kohde ja täytä tiedot manuaalisesti.</CardDescription></CardHeader><CardContent><Button className="w-full" variant="outline" size="lg" onClick={onManual}>Aloita tyhjästä</Button></CardContent></Card></section><p className="mt-8 text-center text-xs text-muted-foreground">Tietoja ei tallenneta tai hyväksytä ilman valintaasi.</p></div></main>;
}
