import type { ConditionArea, RenovationScope, VisualConditionConfidence, VisualConditionErrorCode, VisualConditionRating, VisualConditionRoom } from "./types";

export const visualConditionRatingLabels: Record<VisualConditionRating, string> = { excellent: "Erittäin hyvä", good: "Hyvä", fair: "Tyydyttävä", poor: "Heikko", very_poor: "Erittäin heikko", unknown: "Ei arvioitavissa" };
export const visualConditionConfidenceLabels: Record<VisualConditionConfidence, string> = { high: "Korkea", medium: "Kohtalainen", low: "Matala", unknown: "Ei tiedossa" };
export const renovationScopeLabels: Record<RenovationScope, string> = { none: "Ei näkyvää korjaustarvetta", minor: "Pieni", moderate: "Kohtalainen", major: "Suuri", extensive: "Erittäin laaja", unknown: "Ei arvioitavissa" };
export const visualConditionRoomLabels: Record<VisualConditionRoom, string> = { living_room: "Olohuone", bedroom: "Makuuhuone", kitchen: "Keittiö", bathroom: "Kylpyhuone", toilet: "WC", sauna: "Sauna", entry: "Eteinen", utility_room: "Kodinhoitohuone", balcony: "Parveke", terrace: "Terassi", yard: "Piha", facade: "Julkisivu", garage: "Autokatos tai autotalli", basement: "Kellari", storage: "Varasto", technical_room: "Tekninen tila", other: "Muu tila", unknown: "Tila ei tiedossa" };
export const conditionAreaLabels: Record<ConditionArea, string> = { floor: "Lattia", wall: "Seinä", ceiling: "Sisäkatto", cabinetry: "Kalusteet", countertop: "Työtaso", appliance: "Kodinkone", fixture: "Varuste", electrical_fixture: "Näkyvä sähkökaluste", window: "Ikkuna", door: "Ovi", wet_area: "Märkätila", facade: "Julkisivu", balcony: "Parveke", roof: "Näkyvä vesikatto", foundation: "Sokkeli tai perustus", rainwater_system: "Näkyvä sadevesijärjestelmä", yard: "Piha", general: "Yleiskunto", other: "Muu" };
export const visualConditionErrorLabels: Record<VisualConditionErrorCode, string> = {
  NO_IMAGES: "Lisää vähintään yksi kuva.", IMAGE_ACCESS_DENIED: "Kuvatiedostoa ei voitu lukea.", UNSUPPORTED_FORMAT: "Kuvan tiedostomuotoa ei tueta.", IMAGE_TOO_LARGE: "Kuvatiedosto on liian suuri.", IMAGE_TOO_SMALL: "Kuvan tarkkuus on liian pieni luotettavaan arvioon.", IMAGE_ANALYSIS_FAILED: "Kuvan analysointi epäonnistui.", LOW_IMAGE_QUALITY: "Kuvan laatu rajoittaa arviointia.", NO_ANALYSABLE_CONTENT: "Kuvasta ei löytynyt arvioitavaa kohteen pintaa.", SAFETY_FILTERED: "Kuvaa ei voitu käsitellä turvallisuussuodatuksen vuoksi.", TIMEOUT: "Kuvan analysointi aikakatkaistiin. Yritä uudelleen."
};
